// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metrics.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 3021000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_metrics_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_metrics_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_metrics_2eproto;
namespace rome {
namespace metrics {
class CounterProto;
struct CounterProtoDefaultTypeInternal;
extern CounterProtoDefaultTypeInternal _CounterProto_default_instance_;
class MetricProto;
struct MetricProtoDefaultTypeInternal;
extern MetricProtoDefaultTypeInternal _MetricProto_default_instance_;
class StopwatchProto;
struct StopwatchProtoDefaultTypeInternal;
extern StopwatchProtoDefaultTypeInternal _StopwatchProto_default_instance_;
class SummaryProto;
struct SummaryProtoDefaultTypeInternal;
extern SummaryProtoDefaultTypeInternal _SummaryProto_default_instance_;
}  // namespace metrics
}  // namespace rome
PROTOBUF_NAMESPACE_OPEN
template <>
::rome::metrics::CounterProto* Arena::CreateMaybeMessage<::rome::metrics::CounterProto>(Arena*);
template <>
::rome::metrics::MetricProto* Arena::CreateMaybeMessage<::rome::metrics::MetricProto>(Arena*);
template <>
::rome::metrics::StopwatchProto* Arena::CreateMaybeMessage<::rome::metrics::StopwatchProto>(Arena*);
template <>
::rome::metrics::SummaryProto* Arena::CreateMaybeMessage<::rome::metrics::SummaryProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace rome {
namespace metrics {

// ===================================================================


// -------------------------------------------------------------------

class MetricProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rome.metrics.MetricProto) */ {
 public:
  inline MetricProto() : MetricProto(nullptr) {}
  ~MetricProto() override;
  explicit PROTOBUF_CONSTEXPR MetricProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MetricProto(const MetricProto& from);
  MetricProto(MetricProto&& from) noexcept
    : MetricProto() {
    *this = ::std::move(from);
  }

  inline MetricProto& operator=(const MetricProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetricProto& operator=(MetricProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MetricProto& default_instance() {
    return *internal_default_instance();
  }
  enum MetricCase {
    kCounter = 2,
    kStopwatch = 3,
    kSummary = 4,
    METRIC_NOT_SET = 0,
  };

  static inline const MetricProto* internal_default_instance() {
    return reinterpret_cast<const MetricProto*>(
               &_MetricProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MetricProto& a, MetricProto& b) {
    a.Swap(&b);
  }
  inline void Swap(MetricProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MetricProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MetricProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MetricProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MetricProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MetricProto& from) {
    MetricProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MetricProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "rome.metrics.MetricProto";
  }
  protected:
  explicit MetricProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kCounterFieldNumber = 2,
    kStopwatchFieldNumber = 3,
    kSummaryFieldNumber = 4,
  };
  // optional string name = 1;
  bool has_name() const;
  void clear_name() ;
  const std::string& name() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* ptr);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .rome.metrics.CounterProto counter = 2;
  bool has_counter() const;
  private:
  bool _internal_has_counter() const;

  public:
  void clear_counter() ;
  const ::rome::metrics::CounterProto& counter() const;
  PROTOBUF_NODISCARD ::rome::metrics::CounterProto* release_counter();
  ::rome::metrics::CounterProto* mutable_counter();
  void set_allocated_counter(::rome::metrics::CounterProto* counter);
  private:
  const ::rome::metrics::CounterProto& _internal_counter() const;
  ::rome::metrics::CounterProto* _internal_mutable_counter();
  public:
  void unsafe_arena_set_allocated_counter(
      ::rome::metrics::CounterProto* counter);
  ::rome::metrics::CounterProto* unsafe_arena_release_counter();
  // .rome.metrics.StopwatchProto stopwatch = 3;
  bool has_stopwatch() const;
  private:
  bool _internal_has_stopwatch() const;

  public:
  void clear_stopwatch() ;
  const ::rome::metrics::StopwatchProto& stopwatch() const;
  PROTOBUF_NODISCARD ::rome::metrics::StopwatchProto* release_stopwatch();
  ::rome::metrics::StopwatchProto* mutable_stopwatch();
  void set_allocated_stopwatch(::rome::metrics::StopwatchProto* stopwatch);
  private:
  const ::rome::metrics::StopwatchProto& _internal_stopwatch() const;
  ::rome::metrics::StopwatchProto* _internal_mutable_stopwatch();
  public:
  void unsafe_arena_set_allocated_stopwatch(
      ::rome::metrics::StopwatchProto* stopwatch);
  ::rome::metrics::StopwatchProto* unsafe_arena_release_stopwatch();
  // .rome.metrics.SummaryProto summary = 4;
  bool has_summary() const;
  private:
  bool _internal_has_summary() const;

  public:
  void clear_summary() ;
  const ::rome::metrics::SummaryProto& summary() const;
  PROTOBUF_NODISCARD ::rome::metrics::SummaryProto* release_summary();
  ::rome::metrics::SummaryProto* mutable_summary();
  void set_allocated_summary(::rome::metrics::SummaryProto* summary);
  private:
  const ::rome::metrics::SummaryProto& _internal_summary() const;
  ::rome::metrics::SummaryProto* _internal_mutable_summary();
  public:
  void unsafe_arena_set_allocated_summary(
      ::rome::metrics::SummaryProto* summary);
  ::rome::metrics::SummaryProto* unsafe_arena_release_summary();
  void clear_metric();
  MetricCase metric_case() const;
  // @@protoc_insertion_point(class_scope:rome.metrics.MetricProto)
 private:
  class _Internal;
  void set_has_counter();
  void set_has_stopwatch();
  void set_has_summary();

  inline bool has_metric() const;
  inline void clear_has_metric();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    union MetricUnion {
      constexpr MetricUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::rome::metrics::CounterProto* counter_;
      ::rome::metrics::StopwatchProto* stopwatch_;
      ::rome::metrics::SummaryProto* summary_;
    } metric_;
    ::uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};// -------------------------------------------------------------------

class CounterProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rome.metrics.CounterProto) */ {
 public:
  inline CounterProto() : CounterProto(nullptr) {}
  ~CounterProto() override;
  explicit PROTOBUF_CONSTEXPR CounterProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CounterProto(const CounterProto& from);
  CounterProto(CounterProto&& from) noexcept
    : CounterProto() {
    *this = ::std::move(from);
  }

  inline CounterProto& operator=(const CounterProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline CounterProto& operator=(CounterProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CounterProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const CounterProto* internal_default_instance() {
    return reinterpret_cast<const CounterProto*>(
               &_CounterProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CounterProto& a, CounterProto& b) {
    a.Swap(&b);
  }
  inline void Swap(CounterProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CounterProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CounterProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CounterProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CounterProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CounterProto& from) {
    CounterProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CounterProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "rome.metrics.CounterProto";
  }
  protected:
  explicit CounterProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCountFieldNumber = 1,
  };
  // optional uint64 count = 1;
  bool has_count() const;
  void clear_count() ;
  ::uint64_t count() const;
  void set_count(::uint64_t value);

  private:
  ::uint64_t _internal_count() const;
  void _internal_set_count(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:rome.metrics.CounterProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::uint64_t count_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};// -------------------------------------------------------------------

class StopwatchProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rome.metrics.StopwatchProto) */ {
 public:
  inline StopwatchProto() : StopwatchProto(nullptr) {}
  ~StopwatchProto() override;
  explicit PROTOBUF_CONSTEXPR StopwatchProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StopwatchProto(const StopwatchProto& from);
  StopwatchProto(StopwatchProto&& from) noexcept
    : StopwatchProto() {
    *this = ::std::move(from);
  }

  inline StopwatchProto& operator=(const StopwatchProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopwatchProto& operator=(StopwatchProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopwatchProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopwatchProto* internal_default_instance() {
    return reinterpret_cast<const StopwatchProto*>(
               &_StopwatchProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StopwatchProto& a, StopwatchProto& b) {
    a.Swap(&b);
  }
  inline void Swap(StopwatchProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopwatchProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopwatchProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StopwatchProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StopwatchProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StopwatchProto& from) {
    StopwatchProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StopwatchProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "rome.metrics.StopwatchProto";
  }
  protected:
  explicit StopwatchProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRuntimeNsFieldNumber = 1,
  };
  // optional uint64 runtime_ns = 1;
  bool has_runtime_ns() const;
  void clear_runtime_ns() ;
  ::uint64_t runtime_ns() const;
  void set_runtime_ns(::uint64_t value);

  private:
  ::uint64_t _internal_runtime_ns() const;
  void _internal_set_runtime_ns(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:rome.metrics.StopwatchProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::uint64_t runtime_ns_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};// -------------------------------------------------------------------

class SummaryProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rome.metrics.SummaryProto) */ {
 public:
  inline SummaryProto() : SummaryProto(nullptr) {}
  ~SummaryProto() override;
  explicit PROTOBUF_CONSTEXPR SummaryProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SummaryProto(const SummaryProto& from);
  SummaryProto(SummaryProto&& from) noexcept
    : SummaryProto() {
    *this = ::std::move(from);
  }

  inline SummaryProto& operator=(const SummaryProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline SummaryProto& operator=(SummaryProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SummaryProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const SummaryProto* internal_default_instance() {
    return reinterpret_cast<const SummaryProto*>(
               &_SummaryProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SummaryProto& a, SummaryProto& b) {
    a.Swap(&b);
  }
  inline void Swap(SummaryProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SummaryProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SummaryProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SummaryProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SummaryProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SummaryProto& from) {
    SummaryProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SummaryProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "rome.metrics.SummaryProto";
  }
  protected:
  explicit SummaryProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnitsFieldNumber = 1,
    kMeanFieldNumber = 2,
    kStddevFieldNumber = 3,
    kMinFieldNumber = 4,
    kP50FieldNumber = 6,
    kP90FieldNumber = 7,
    kP95FieldNumber = 8,
    kP99FieldNumber = 9,
    kP999FieldNumber = 10,
    kMaxFieldNumber = 11,
    kCountFieldNumber = 12,
  };
  // optional string units = 1;
  bool has_units() const;
  void clear_units() ;
  const std::string& units() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_units(Arg_&& arg, Args_... args);
  std::string* mutable_units();
  PROTOBUF_NODISCARD std::string* release_units();
  void set_allocated_units(std::string* ptr);

  private:
  const std::string& _internal_units() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_units(
      const std::string& value);
  std::string* _internal_mutable_units();

  public:
  // optional double mean = 2;
  bool has_mean() const;
  void clear_mean() ;
  double mean() const;
  void set_mean(double value);

  private:
  double _internal_mean() const;
  void _internal_set_mean(double value);

  public:
  // optional double stddev = 3;
  bool has_stddev() const;
  void clear_stddev() ;
  double stddev() const;
  void set_stddev(double value);

  private:
  double _internal_stddev() const;
  void _internal_set_stddev(double value);

  public:
  // optional double min = 4;
  bool has_min() const;
  void clear_min() ;
  double min() const;
  void set_min(double value);

  private:
  double _internal_min() const;
  void _internal_set_min(double value);

  public:
  // optional double p50 = 6;
  bool has_p50() const;
  void clear_p50() ;
  double p50() const;
  void set_p50(double value);

  private:
  double _internal_p50() const;
  void _internal_set_p50(double value);

  public:
  // optional double p90 = 7;
  bool has_p90() const;
  void clear_p90() ;
  double p90() const;
  void set_p90(double value);

  private:
  double _internal_p90() const;
  void _internal_set_p90(double value);

  public:
  // optional double p95 = 8;
  bool has_p95() const;
  void clear_p95() ;
  double p95() const;
  void set_p95(double value);

  private:
  double _internal_p95() const;
  void _internal_set_p95(double value);

  public:
  // optional double p99 = 9;
  bool has_p99() const;
  void clear_p99() ;
  double p99() const;
  void set_p99(double value);

  private:
  double _internal_p99() const;
  void _internal_set_p99(double value);

  public:
  // optional double p999 = 10;
  bool has_p999() const;
  void clear_p999() ;
  double p999() const;
  void set_p999(double value);

  private:
  double _internal_p999() const;
  void _internal_set_p999(double value);

  public:
  // optional double max = 11;
  bool has_max() const;
  void clear_max() ;
  double max() const;
  void set_max(double value);

  private:
  double _internal_max() const;
  void _internal_set_max(double value);

  public:
  // optional uint64 count = 12;
  bool has_count() const;
  void clear_count() ;
  ::uint64_t count() const;
  void set_count(::uint64_t value);

  private:
  ::uint64_t _internal_count() const;
  void _internal_set_count(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:rome.metrics.SummaryProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr units_;
    double mean_;
    double stddev_;
    double min_;
    double p50_;
    double p90_;
    double p95_;
    double p99_;
    double p999_;
    double max_;
    ::uint64_t count_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_metrics_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MetricProto

// optional string name = 1;
inline bool MetricProto::has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void MetricProto::clear_name() {
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MetricProto::name() const {
  // @@protoc_insertion_point(field_get:rome.metrics.MetricProto.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MetricProto::set_name(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rome.metrics.MetricProto.name)
}
inline std::string* MetricProto::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:rome.metrics.MetricProto.name)
  return _s;
}
inline const std::string& MetricProto::_internal_name() const {
  return _impl_.name_.Get();
}
inline void MetricProto::_internal_set_name(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* MetricProto::_internal_mutable_name() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArenaForAllocation());
}
inline std::string* MetricProto::release_name() {
  // @@protoc_insertion_point(field_release:rome.metrics.MetricProto.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void MetricProto::set_allocated_name(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rome.metrics.MetricProto.name)
}

// .rome.metrics.CounterProto counter = 2;
inline bool MetricProto::has_counter() const {
  return metric_case() == kCounter;
}
inline bool MetricProto::_internal_has_counter() const {
  return metric_case() == kCounter;
}
inline void MetricProto::set_has_counter() {
  _impl_._oneof_case_[0] = kCounter;
}
inline void MetricProto::clear_counter() {
  if (metric_case() == kCounter) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.metric_.counter_;
    }
    clear_has_metric();
  }
}
inline ::rome::metrics::CounterProto* MetricProto::release_counter() {
  // @@protoc_insertion_point(field_release:rome.metrics.MetricProto.counter)
  if (metric_case() == kCounter) {
    clear_has_metric();
    ::rome::metrics::CounterProto* temp = _impl_.metric_.counter_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.metric_.counter_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rome::metrics::CounterProto& MetricProto::_internal_counter() const {
  return metric_case() == kCounter
      ? *_impl_.metric_.counter_
      : reinterpret_cast< ::rome::metrics::CounterProto&>(::rome::metrics::_CounterProto_default_instance_);
}
inline const ::rome::metrics::CounterProto& MetricProto::counter() const {
  // @@protoc_insertion_point(field_get:rome.metrics.MetricProto.counter)
  return _internal_counter();
}
inline ::rome::metrics::CounterProto* MetricProto::unsafe_arena_release_counter() {
  // @@protoc_insertion_point(field_unsafe_arena_release:rome.metrics.MetricProto.counter)
  if (metric_case() == kCounter) {
    clear_has_metric();
    ::rome::metrics::CounterProto* temp = _impl_.metric_.counter_;
    _impl_.metric_.counter_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void MetricProto::unsafe_arena_set_allocated_counter(::rome::metrics::CounterProto* counter) {
  clear_metric();
  if (counter) {
    set_has_counter();
    _impl_.metric_.counter_ = counter;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rome.metrics.MetricProto.counter)
}
inline ::rome::metrics::CounterProto* MetricProto::_internal_mutable_counter() {
  if (metric_case() != kCounter) {
    clear_metric();
    set_has_counter();
    _impl_.metric_.counter_ = CreateMaybeMessage< ::rome::metrics::CounterProto >(GetArenaForAllocation());
  }
  return _impl_.metric_.counter_;
}
inline ::rome::metrics::CounterProto* MetricProto::mutable_counter() {
  ::rome::metrics::CounterProto* _msg = _internal_mutable_counter();
  // @@protoc_insertion_point(field_mutable:rome.metrics.MetricProto.counter)
  return _msg;
}

// .rome.metrics.StopwatchProto stopwatch = 3;
inline bool MetricProto::has_stopwatch() const {
  return metric_case() == kStopwatch;
}
inline bool MetricProto::_internal_has_stopwatch() const {
  return metric_case() == kStopwatch;
}
inline void MetricProto::set_has_stopwatch() {
  _impl_._oneof_case_[0] = kStopwatch;
}
inline void MetricProto::clear_stopwatch() {
  if (metric_case() == kStopwatch) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.metric_.stopwatch_;
    }
    clear_has_metric();
  }
}
inline ::rome::metrics::StopwatchProto* MetricProto::release_stopwatch() {
  // @@protoc_insertion_point(field_release:rome.metrics.MetricProto.stopwatch)
  if (metric_case() == kStopwatch) {
    clear_has_metric();
    ::rome::metrics::StopwatchProto* temp = _impl_.metric_.stopwatch_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.metric_.stopwatch_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rome::metrics::StopwatchProto& MetricProto::_internal_stopwatch() const {
  return metric_case() == kStopwatch
      ? *_impl_.metric_.stopwatch_
      : reinterpret_cast< ::rome::metrics::StopwatchProto&>(::rome::metrics::_StopwatchProto_default_instance_);
}
inline const ::rome::metrics::StopwatchProto& MetricProto::stopwatch() const {
  // @@protoc_insertion_point(field_get:rome.metrics.MetricProto.stopwatch)
  return _internal_stopwatch();
}
inline ::rome::metrics::StopwatchProto* MetricProto::unsafe_arena_release_stopwatch() {
  // @@protoc_insertion_point(field_unsafe_arena_release:rome.metrics.MetricProto.stopwatch)
  if (metric_case() == kStopwatch) {
    clear_has_metric();
    ::rome::metrics::StopwatchProto* temp = _impl_.metric_.stopwatch_;
    _impl_.metric_.stopwatch_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void MetricProto::unsafe_arena_set_allocated_stopwatch(::rome::metrics::StopwatchProto* stopwatch) {
  clear_metric();
  if (stopwatch) {
    set_has_stopwatch();
    _impl_.metric_.stopwatch_ = stopwatch;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rome.metrics.MetricProto.stopwatch)
}
inline ::rome::metrics::StopwatchProto* MetricProto::_internal_mutable_stopwatch() {
  if (metric_case() != kStopwatch) {
    clear_metric();
    set_has_stopwatch();
    _impl_.metric_.stopwatch_ = CreateMaybeMessage< ::rome::metrics::StopwatchProto >(GetArenaForAllocation());
  }
  return _impl_.metric_.stopwatch_;
}
inline ::rome::metrics::StopwatchProto* MetricProto::mutable_stopwatch() {
  ::rome::metrics::StopwatchProto* _msg = _internal_mutable_stopwatch();
  // @@protoc_insertion_point(field_mutable:rome.metrics.MetricProto.stopwatch)
  return _msg;
}

// .rome.metrics.SummaryProto summary = 4;
inline bool MetricProto::has_summary() const {
  return metric_case() == kSummary;
}
inline bool MetricProto::_internal_has_summary() const {
  return metric_case() == kSummary;
}
inline void MetricProto::set_has_summary() {
  _impl_._oneof_case_[0] = kSummary;
}
inline void MetricProto::clear_summary() {
  if (metric_case() == kSummary) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.metric_.summary_;
    }
    clear_has_metric();
  }
}
inline ::rome::metrics::SummaryProto* MetricProto::release_summary() {
  // @@protoc_insertion_point(field_release:rome.metrics.MetricProto.summary)
  if (metric_case() == kSummary) {
    clear_has_metric();
    ::rome::metrics::SummaryProto* temp = _impl_.metric_.summary_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.metric_.summary_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rome::metrics::SummaryProto& MetricProto::_internal_summary() const {
  return metric_case() == kSummary
      ? *_impl_.metric_.summary_
      : reinterpret_cast< ::rome::metrics::SummaryProto&>(::rome::metrics::_SummaryProto_default_instance_);
}
inline const ::rome::metrics::SummaryProto& MetricProto::summary() const {
  // @@protoc_insertion_point(field_get:rome.metrics.MetricProto.summary)
  return _internal_summary();
}
inline ::rome::metrics::SummaryProto* MetricProto::unsafe_arena_release_summary() {
  // @@protoc_insertion_point(field_unsafe_arena_release:rome.metrics.MetricProto.summary)
  if (metric_case() == kSummary) {
    clear_has_metric();
    ::rome::metrics::SummaryProto* temp = _impl_.metric_.summary_;
    _impl_.metric_.summary_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void MetricProto::unsafe_arena_set_allocated_summary(::rome::metrics::SummaryProto* summary) {
  clear_metric();
  if (summary) {
    set_has_summary();
    _impl_.metric_.summary_ = summary;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rome.metrics.MetricProto.summary)
}
inline ::rome::metrics::SummaryProto* MetricProto::_internal_mutable_summary() {
  if (metric_case() != kSummary) {
    clear_metric();
    set_has_summary();
    _impl_.metric_.summary_ = CreateMaybeMessage< ::rome::metrics::SummaryProto >(GetArenaForAllocation());
  }
  return _impl_.metric_.summary_;
}
inline ::rome::metrics::SummaryProto* MetricProto::mutable_summary() {
  ::rome::metrics::SummaryProto* _msg = _internal_mutable_summary();
  // @@protoc_insertion_point(field_mutable:rome.metrics.MetricProto.summary)
  return _msg;
}

inline bool MetricProto::has_metric() const {
  return metric_case() != METRIC_NOT_SET;
}
inline void MetricProto::clear_has_metric() {
  _impl_._oneof_case_[0] = METRIC_NOT_SET;
}
inline MetricProto::MetricCase MetricProto::metric_case() const {
  return MetricProto::MetricCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// CounterProto

// optional uint64 count = 1;
inline bool CounterProto::has_count() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void CounterProto::clear_count() {
  _impl_.count_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t CounterProto::count() const {
  // @@protoc_insertion_point(field_get:rome.metrics.CounterProto.count)
  return _internal_count();
}
inline void CounterProto::set_count(::uint64_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:rome.metrics.CounterProto.count)
}
inline ::uint64_t CounterProto::_internal_count() const {
  return _impl_.count_;
}
inline void CounterProto::_internal_set_count(::uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.count_ = value;
}

// -------------------------------------------------------------------

// StopwatchProto

// optional uint64 runtime_ns = 1;
inline bool StopwatchProto::has_runtime_ns() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void StopwatchProto::clear_runtime_ns() {
  _impl_.runtime_ns_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t StopwatchProto::runtime_ns() const {
  // @@protoc_insertion_point(field_get:rome.metrics.StopwatchProto.runtime_ns)
  return _internal_runtime_ns();
}
inline void StopwatchProto::set_runtime_ns(::uint64_t value) {
  _internal_set_runtime_ns(value);
  // @@protoc_insertion_point(field_set:rome.metrics.StopwatchProto.runtime_ns)
}
inline ::uint64_t StopwatchProto::_internal_runtime_ns() const {
  return _impl_.runtime_ns_;
}
inline void StopwatchProto::_internal_set_runtime_ns(::uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.runtime_ns_ = value;
}

// -------------------------------------------------------------------

// SummaryProto

// optional string units = 1;
inline bool SummaryProto::has_units() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SummaryProto::clear_units() {
  _impl_.units_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SummaryProto::units() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.units)
  return _internal_units();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SummaryProto::set_units(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.units_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.units)
}
inline std::string* SummaryProto::mutable_units() {
  std::string* _s = _internal_mutable_units();
  // @@protoc_insertion_point(field_mutable:rome.metrics.SummaryProto.units)
  return _s;
}
inline const std::string& SummaryProto::_internal_units() const {
  return _impl_.units_.Get();
}
inline void SummaryProto::_internal_set_units(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.units_.Set(value, GetArenaForAllocation());
}
inline std::string* SummaryProto::_internal_mutable_units() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.units_.Mutable( GetArenaForAllocation());
}
inline std::string* SummaryProto::release_units() {
  // @@protoc_insertion_point(field_release:rome.metrics.SummaryProto.units)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.units_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.units_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void SummaryProto::set_allocated_units(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.units_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.units_.IsDefault()) {
          _impl_.units_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rome.metrics.SummaryProto.units)
}

// optional double mean = 2;
inline bool SummaryProto::has_mean() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SummaryProto::clear_mean() {
  _impl_.mean_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double SummaryProto::mean() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.mean)
  return _internal_mean();
}
inline void SummaryProto::set_mean(double value) {
  _internal_set_mean(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.mean)
}
inline double SummaryProto::_internal_mean() const {
  return _impl_.mean_;
}
inline void SummaryProto::_internal_set_mean(double value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.mean_ = value;
}

// optional double stddev = 3;
inline bool SummaryProto::has_stddev() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SummaryProto::clear_stddev() {
  _impl_.stddev_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double SummaryProto::stddev() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.stddev)
  return _internal_stddev();
}
inline void SummaryProto::set_stddev(double value) {
  _internal_set_stddev(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.stddev)
}
inline double SummaryProto::_internal_stddev() const {
  return _impl_.stddev_;
}
inline void SummaryProto::_internal_set_stddev(double value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.stddev_ = value;
}

// optional double min = 4;
inline bool SummaryProto::has_min() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void SummaryProto::clear_min() {
  _impl_.min_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline double SummaryProto::min() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.min)
  return _internal_min();
}
inline void SummaryProto::set_min(double value) {
  _internal_set_min(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.min)
}
inline double SummaryProto::_internal_min() const {
  return _impl_.min_;
}
inline void SummaryProto::_internal_set_min(double value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.min_ = value;
}

// optional double p50 = 6;
inline bool SummaryProto::has_p50() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void SummaryProto::clear_p50() {
  _impl_.p50_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline double SummaryProto::p50() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.p50)
  return _internal_p50();
}
inline void SummaryProto::set_p50(double value) {
  _internal_set_p50(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.p50)
}
inline double SummaryProto::_internal_p50() const {
  return _impl_.p50_;
}
inline void SummaryProto::_internal_set_p50(double value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.p50_ = value;
}

// optional double p90 = 7;
inline bool SummaryProto::has_p90() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void SummaryProto::clear_p90() {
  _impl_.p90_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline double SummaryProto::p90() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.p90)
  return _internal_p90();
}
inline void SummaryProto::set_p90(double value) {
  _internal_set_p90(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.p90)
}
inline double SummaryProto::_internal_p90() const {
  return _impl_.p90_;
}
inline void SummaryProto::_internal_set_p90(double value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.p90_ = value;
}

// optional double p95 = 8;
inline bool SummaryProto::has_p95() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void SummaryProto::clear_p95() {
  _impl_.p95_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline double SummaryProto::p95() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.p95)
  return _internal_p95();
}
inline void SummaryProto::set_p95(double value) {
  _internal_set_p95(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.p95)
}
inline double SummaryProto::_internal_p95() const {
  return _impl_.p95_;
}
inline void SummaryProto::_internal_set_p95(double value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.p95_ = value;
}

// optional double p99 = 9;
inline bool SummaryProto::has_p99() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void SummaryProto::clear_p99() {
  _impl_.p99_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline double SummaryProto::p99() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.p99)
  return _internal_p99();
}
inline void SummaryProto::set_p99(double value) {
  _internal_set_p99(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.p99)
}
inline double SummaryProto::_internal_p99() const {
  return _impl_.p99_;
}
inline void SummaryProto::_internal_set_p99(double value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.p99_ = value;
}

// optional double p999 = 10;
inline bool SummaryProto::has_p999() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void SummaryProto::clear_p999() {
  _impl_.p999_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline double SummaryProto::p999() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.p999)
  return _internal_p999();
}
inline void SummaryProto::set_p999(double value) {
  _internal_set_p999(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.p999)
}
inline double SummaryProto::_internal_p999() const {
  return _impl_.p999_;
}
inline void SummaryProto::_internal_set_p999(double value) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.p999_ = value;
}

// optional double max = 11;
inline bool SummaryProto::has_max() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void SummaryProto::clear_max() {
  _impl_.max_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline double SummaryProto::max() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.max)
  return _internal_max();
}
inline void SummaryProto::set_max(double value) {
  _internal_set_max(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.max)
}
inline double SummaryProto::_internal_max() const {
  return _impl_.max_;
}
inline void SummaryProto::_internal_set_max(double value) {
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.max_ = value;
}

// optional uint64 count = 12;
inline bool SummaryProto::has_count() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void SummaryProto::clear_count() {
  _impl_.count_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline ::uint64_t SummaryProto::count() const {
  // @@protoc_insertion_point(field_get:rome.metrics.SummaryProto.count)
  return _internal_count();
}
inline void SummaryProto::set_count(::uint64_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:rome.metrics.SummaryProto.count)
}
inline ::uint64_t SummaryProto::_internal_count() const {
  return _impl_.count_;
}
inline void SummaryProto::_internal_set_count(::uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.count_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace metrics
}  // namespace rome


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_metrics_2eproto_2epb_2eh
