// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rdma.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rdma_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_rdma_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 3021000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_rdma_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rdma_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_rdma_2eproto;
namespace rome {
namespace rdma {
class RemoteObjectProto;
struct RemoteObjectProtoDefaultTypeInternal;
extern RemoteObjectProtoDefaultTypeInternal _RemoteObjectProto_default_instance_;
}  // namespace rdma
}  // namespace rome
PROTOBUF_NAMESPACE_OPEN
template <>
::rome::rdma::RemoteObjectProto* Arena::CreateMaybeMessage<::rome::rdma::RemoteObjectProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace rome {
namespace rdma {

// ===================================================================


// -------------------------------------------------------------------

class RemoteObjectProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rome.rdma.RemoteObjectProto) */ {
 public:
  inline RemoteObjectProto() : RemoteObjectProto(nullptr) {}
  ~RemoteObjectProto() override;
  explicit PROTOBUF_CONSTEXPR RemoteObjectProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RemoteObjectProto(const RemoteObjectProto& from);
  RemoteObjectProto(RemoteObjectProto&& from) noexcept
    : RemoteObjectProto() {
    *this = ::std::move(from);
  }

  inline RemoteObjectProto& operator=(const RemoteObjectProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline RemoteObjectProto& operator=(RemoteObjectProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RemoteObjectProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const RemoteObjectProto* internal_default_instance() {
    return reinterpret_cast<const RemoteObjectProto*>(
               &_RemoteObjectProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RemoteObjectProto& a, RemoteObjectProto& b) {
    a.Swap(&b);
  }
  inline void Swap(RemoteObjectProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RemoteObjectProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RemoteObjectProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RemoteObjectProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RemoteObjectProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RemoteObjectProto& from) {
    RemoteObjectProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RemoteObjectProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "rome.rdma.RemoteObjectProto";
  }
  protected:
  explicit RemoteObjectProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kRaddrFieldNumber = 2,
    kSizeFieldNumber = 3,
    kLkeyFieldNumber = 4,
    kRkeyFieldNumber = 5,
  };
  // optional string id = 1;
  bool has_id() const;
  void clear_id() ;
  const std::string& id() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* ptr);

  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(
      const std::string& value);
  std::string* _internal_mutable_id();

  public:
  // optional uint64 raddr = 2;
  bool has_raddr() const;
  void clear_raddr() ;
  ::uint64_t raddr() const;
  void set_raddr(::uint64_t value);

  private:
  ::uint64_t _internal_raddr() const;
  void _internal_set_raddr(::uint64_t value);

  public:
  // optional uint32 size = 3;
  bool has_size() const;
  void clear_size() ;
  ::uint32_t size() const;
  void set_size(::uint32_t value);

  private:
  ::uint32_t _internal_size() const;
  void _internal_set_size(::uint32_t value);

  public:
  // optional uint32 lkey = 4;
  bool has_lkey() const;
  void clear_lkey() ;
  ::uint32_t lkey() const;
  void set_lkey(::uint32_t value);

  private:
  ::uint32_t _internal_lkey() const;
  void _internal_set_lkey(::uint32_t value);

  public:
  // optional uint32 rkey = 5;
  bool has_rkey() const;
  void clear_rkey() ;
  ::uint32_t rkey() const;
  void set_rkey(::uint32_t value);

  private:
  ::uint32_t _internal_rkey() const;
  void _internal_set_rkey(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:rome.rdma.RemoteObjectProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::uint64_t raddr_;
    ::uint32_t size_;
    ::uint32_t lkey_;
    ::uint32_t rkey_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rdma_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RemoteObjectProto

// optional string id = 1;
inline bool RemoteObjectProto::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void RemoteObjectProto::clear_id() {
  _impl_.id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RemoteObjectProto::id() const {
  // @@protoc_insertion_point(field_get:rome.rdma.RemoteObjectProto.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RemoteObjectProto::set_id(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rome.rdma.RemoteObjectProto.id)
}
inline std::string* RemoteObjectProto::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:rome.rdma.RemoteObjectProto.id)
  return _s;
}
inline const std::string& RemoteObjectProto::_internal_id() const {
  return _impl_.id_.Get();
}
inline void RemoteObjectProto::_internal_set_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* RemoteObjectProto::_internal_mutable_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.id_.Mutable( GetArenaForAllocation());
}
inline std::string* RemoteObjectProto::release_id() {
  // @@protoc_insertion_point(field_release:rome.rdma.RemoteObjectProto.id)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.id_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void RemoteObjectProto::set_allocated_id(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.id_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.id_.IsDefault()) {
          _impl_.id_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rome.rdma.RemoteObjectProto.id)
}

// optional uint64 raddr = 2;
inline bool RemoteObjectProto::has_raddr() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void RemoteObjectProto::clear_raddr() {
  _impl_.raddr_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint64_t RemoteObjectProto::raddr() const {
  // @@protoc_insertion_point(field_get:rome.rdma.RemoteObjectProto.raddr)
  return _internal_raddr();
}
inline void RemoteObjectProto::set_raddr(::uint64_t value) {
  _internal_set_raddr(value);
  // @@protoc_insertion_point(field_set:rome.rdma.RemoteObjectProto.raddr)
}
inline ::uint64_t RemoteObjectProto::_internal_raddr() const {
  return _impl_.raddr_;
}
inline void RemoteObjectProto::_internal_set_raddr(::uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.raddr_ = value;
}

// optional uint32 size = 3;
inline bool RemoteObjectProto::has_size() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void RemoteObjectProto::clear_size() {
  _impl_.size_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t RemoteObjectProto::size() const {
  // @@protoc_insertion_point(field_get:rome.rdma.RemoteObjectProto.size)
  return _internal_size();
}
inline void RemoteObjectProto::set_size(::uint32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:rome.rdma.RemoteObjectProto.size)
}
inline ::uint32_t RemoteObjectProto::_internal_size() const {
  return _impl_.size_;
}
inline void RemoteObjectProto::_internal_set_size(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.size_ = value;
}

// optional uint32 lkey = 4;
inline bool RemoteObjectProto::has_lkey() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void RemoteObjectProto::clear_lkey() {
  _impl_.lkey_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint32_t RemoteObjectProto::lkey() const {
  // @@protoc_insertion_point(field_get:rome.rdma.RemoteObjectProto.lkey)
  return _internal_lkey();
}
inline void RemoteObjectProto::set_lkey(::uint32_t value) {
  _internal_set_lkey(value);
  // @@protoc_insertion_point(field_set:rome.rdma.RemoteObjectProto.lkey)
}
inline ::uint32_t RemoteObjectProto::_internal_lkey() const {
  return _impl_.lkey_;
}
inline void RemoteObjectProto::_internal_set_lkey(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.lkey_ = value;
}

// optional uint32 rkey = 5;
inline bool RemoteObjectProto::has_rkey() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void RemoteObjectProto::clear_rkey() {
  _impl_.rkey_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::uint32_t RemoteObjectProto::rkey() const {
  // @@protoc_insertion_point(field_get:rome.rdma.RemoteObjectProto.rkey)
  return _internal_rkey();
}
inline void RemoteObjectProto::set_rkey(::uint32_t value) {
  _internal_set_rkey(value);
  // @@protoc_insertion_point(field_set:rome.rdma.RemoteObjectProto.rkey)
}
inline ::uint32_t RemoteObjectProto::_internal_rkey() const {
  return _impl_.rkey_;
}
inline void RemoteObjectProto::_internal_set_rkey(::uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.rkey_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace rdma
}  // namespace rome


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_rdma_2eproto_2epb_2eh
