// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rdma.proto

#include "rdma.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace rome {
namespace rdma {
PROTOBUF_CONSTEXPR RemoteObjectProto::RemoteObjectProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.id_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.raddr_)*/ ::uint64_t{0u}

  , /*decltype(_impl_.size_)*/ 0u

  , /*decltype(_impl_.lkey_)*/ 0u

  , /*decltype(_impl_.rkey_)*/ 0u
} {}
struct RemoteObjectProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RemoteObjectProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RemoteObjectProtoDefaultTypeInternal() {}
  union {
    RemoteObjectProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RemoteObjectProtoDefaultTypeInternal _RemoteObjectProto_default_instance_;
}  // namespace rdma
}  // namespace rome
static ::_pb::Metadata file_level_metadata_rdma_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_rdma_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_rdma_2eproto = nullptr;
const ::uint32_t TableStruct_rdma_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::rome::rdma::RemoteObjectProto, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::rome::rdma::RemoteObjectProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rome::rdma::RemoteObjectProto, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::rome::rdma::RemoteObjectProto, _impl_.raddr_),
    PROTOBUF_FIELD_OFFSET(::rome::rdma::RemoteObjectProto, _impl_.size_),
    PROTOBUF_FIELD_OFFSET(::rome::rdma::RemoteObjectProto, _impl_.lkey_),
    PROTOBUF_FIELD_OFFSET(::rome::rdma::RemoteObjectProto, _impl_.rkey_),
    0,
    1,
    2,
    3,
    4,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 13, -1, sizeof(::rome::rdma::RemoteObjectProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::rome::rdma::_RemoteObjectProto_default_instance_._instance,
};
const char descriptor_table_protodef_rdma_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\nrdma.proto\022\trome.rdma\"X\n\021RemoteObjectP"
    "roto\022\n\n\002id\030\001 \001(\t\022\r\n\005raddr\030\002 \001(\004\022\014\n\004size\030"
    "\003 \001(\r\022\014\n\004lkey\030\004 \001(\r\022\014\n\004rkey\030\005 \001(\r"
};
static ::absl::once_flag descriptor_table_rdma_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_rdma_2eproto = {
    false,
    false,
    113,
    descriptor_table_protodef_rdma_2eproto,
    "rdma.proto",
    &descriptor_table_rdma_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_rdma_2eproto::offsets,
    file_level_metadata_rdma_2eproto,
    file_level_enum_descriptors_rdma_2eproto,
    file_level_service_descriptors_rdma_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_rdma_2eproto_getter() {
  return &descriptor_table_rdma_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_rdma_2eproto(&descriptor_table_rdma_2eproto);
namespace rome {
namespace rdma {
// ===================================================================

class RemoteObjectProto::_Internal {
 public:
  using HasBits = decltype(std::declval<RemoteObjectProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(RemoteObjectProto, _impl_._has_bits_);
  static void set_has_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_raddr(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_size(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_lkey(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_rkey(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

RemoteObjectProto::RemoteObjectProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rome.rdma.RemoteObjectProto)
}
RemoteObjectProto::RemoteObjectProto(const RemoteObjectProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RemoteObjectProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_) {}

    , decltype(_impl_.raddr_) {}

    , decltype(_impl_.size_) {}

    , decltype(_impl_.lkey_) {}

    , decltype(_impl_.rkey_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.id_.Set(from._internal_id(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.raddr_, &from._impl_.raddr_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.rkey_) -
    reinterpret_cast<char*>(&_impl_.raddr_)) + sizeof(_impl_.rkey_));
  // @@protoc_insertion_point(copy_constructor:rome.rdma.RemoteObjectProto)
}

inline void RemoteObjectProto::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_) {}

    , decltype(_impl_.raddr_) { ::uint64_t{0u} }

    , decltype(_impl_.size_) { 0u }

    , decltype(_impl_.lkey_) { 0u }

    , decltype(_impl_.rkey_) { 0u }

  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RemoteObjectProto::~RemoteObjectProto() {
  // @@protoc_insertion_point(destructor:rome.rdma.RemoteObjectProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RemoteObjectProto::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
}

void RemoteObjectProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RemoteObjectProto::Clear() {
// @@protoc_insertion_point(message_clear_start:rome.rdma.RemoteObjectProto)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.id_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000001eu) {
    ::memset(&_impl_.raddr_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.rkey_) -
        reinterpret_cast<char*>(&_impl_.raddr_)) + sizeof(_impl_.rkey_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RemoteObjectProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "rome.rdma.RemoteObjectProto.id");
          #endif  // !NDEBUG
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint64 raddr = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_raddr(&has_bits);
          _impl_.raddr_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 size = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _Internal::set_has_size(&has_bits);
          _impl_.size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 lkey = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 32)) {
          _Internal::set_has_lkey(&has_bits);
          _impl_.lkey_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 rkey = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 40)) {
          _Internal::set_has_rkey(&has_bits);
          _impl_.rkey_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* RemoteObjectProto::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rome.rdma.RemoteObjectProto)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string id = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_id();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "rome.rdma.RemoteObjectProto.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional uint64 raddr = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_raddr(), target);
  }

  // optional uint32 size = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_size(), target);
  }

  // optional uint32 lkey = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_lkey(), target);
  }

  // optional uint32 rkey = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_rkey(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rome.rdma.RemoteObjectProto)
  return target;
}

::size_t RemoteObjectProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rome.rdma.RemoteObjectProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    // optional string id = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_id());
    }

    // optional uint64 raddr = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_raddr());
    }

    // optional uint32 size = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_size());
    }

    // optional uint32 lkey = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_lkey());
    }

    // optional uint32 rkey = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_rkey());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RemoteObjectProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RemoteObjectProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RemoteObjectProto::GetClassData() const { return &_class_data_; }


void RemoteObjectProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RemoteObjectProto*>(&to_msg);
  auto& from = static_cast<const RemoteObjectProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rome.rdma.RemoteObjectProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_id(from._internal_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.raddr_ = from._impl_.raddr_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.size_ = from._impl_.size_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.lkey_ = from._impl_.lkey_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.rkey_ = from._impl_.rkey_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RemoteObjectProto::CopyFrom(const RemoteObjectProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rome.rdma.RemoteObjectProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RemoteObjectProto::IsInitialized() const {
  return true;
}

void RemoteObjectProto::InternalSwap(RemoteObjectProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, lhs_arena,
                                       &other->_impl_.id_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RemoteObjectProto, _impl_.rkey_)
      + sizeof(RemoteObjectProto::_impl_.rkey_)
      - PROTOBUF_FIELD_OFFSET(RemoteObjectProto, _impl_.raddr_)>(
          reinterpret_cast<char*>(&_impl_.raddr_),
          reinterpret_cast<char*>(&other->_impl_.raddr_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RemoteObjectProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_rdma_2eproto_getter, &descriptor_table_rdma_2eproto_once,
      file_level_metadata_rdma_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rdma
}  // namespace rome
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rome::rdma::RemoteObjectProto*
Arena::CreateMaybeMessage< ::rome::rdma::RemoteObjectProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rome::rdma::RemoteObjectProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
